// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/application/sections/AboutSection.vue')['default']
    Backdrop: typeof import('./components/ui/navigation/Backdrop.vue')['default']
    Background: typeof import('./components/application/Background.vue')['default']
    Container: typeof import('./components/layout/Container.vue')['default']
    Content: typeof import('./components/layout/Content.vue')['default']
    FaceImage: typeof import('./components/application/FaceImage.vue')['default']
    Hamburguer: typeof import('./components/ui/button/Hamburguer.vue')['default']
    Header: typeof import('./components/ui/navigation/Header.vue')['default']
    HeroSection: typeof import('./components/application/sections/HeroSection.vue')['default']
    JButton: typeof import('./components/ui/button/JButton.vue')['default']
    JCard: typeof import('./components/ui/card/JCard.vue')['default']
    JInput: typeof import('./components/ui/input/JInput.vue')['default']
    JSection: typeof import('./components/layout/JSection.vue')['default']
    JTimeline: typeof import('./components/ui/timeline/JTimeline.vue')['default']
    JTimelineItem: typeof import('./components/ui/timeline/JTimelineItem.vue')['default']
    Logo: typeof import('./components/application/Logo.vue')['default']
    MapBackground: typeof import('./components/application/MapBackground.vue')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    MdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    Navigation: typeof import('./components/ui/navigation/Navigation.vue')['default']
    NavItem: typeof import('./components/ui/navigation/NavItem.vue')['default']
    Page: typeof import('./components/layout/Page.vue')['default']
    ToggleDarkButton: typeof import('./components/application/ToggleDarkButton.vue')['default']
    UseIntersectionObserver: typeof import('./components/ui/misc/UseIntersectionObserver.vue')['default']
  }
}

export { }
