// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./components/layout/Container.vue')['default']
    JsHeader: typeof import('./components/navigation/JsHeader.vue')['default']
    MyButton: typeof import('./components/MyButton.vue')['default']
  }
}

export { }
